import mongoose from 'mongoose';

// Mirrors Click's Merchant Shop-API transaction lifecycle: Click calls our webhook twice per
// payment attempt - action=0 (Prepare, before charging the card) then action=1 (Complete,
// after the charge succeeds or fails on Click's side). State values here are our own bookkeeping,
// echoed into idempotent replies rather than Click's own vocabulary:
// 0 = prepared (pending), 1 = completed (paid), -1 = cancelled while pending (Complete reported
// a Click-side failure), -2 = cancelled after having been completed (a later reversal).
const clickTransactionSchema = new mongoose.Schema(
  {
    // Click's own transaction id for this specific payment attempt - the real unique key, since
    // a user can retry a failed payment and get a new clickTransId against the same order.
    clickTransId: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    // Our own opaque reference string, built client-side as "<userId>:<planKey>:<nonce>" when
    // constructing the Click checkout redirect (see ClickCheckoutButton.tsx) - not guaranteed
    // unique on its own (a retried attempt reuses it with a new clickTransId), so only indexed,
    // not a unique key.
    merchantTransId: {
      type: String,
      required: true,
      index: true,
    },
    // Generated by us during Prepare and echoed back by Click on the matching Complete call -
    // this is what actually links the two webhook calls together for one attempt.
    merchantPrepareId: {
      type: String,
      default: '',
    },
    user: {
      type: mongoose.Schema.ObjectId,
      ref: 'User',
      required: true,
    },
    plan: {
      type: String,
      enum: ['learner', 'family', 'teaching'],
      required: true,
    },
    // Whole so'm (Click's native unit) - unlike Payme, which uses tiyin.
    amount: {
      type: Number,
      required: true,
    },
    state: {
      type: Number,
      enum: [0, 1, -1, -2],
      default: 0,
    },
    createTime: {
      type: Number,
      required: true,
    },
    performTime: {
      type: Number,
      default: 0,
    },
    cancelTime: {
      type: Number,
      default: 0,
    },
  },
  { timestamps: true }
);

export default mongoose.model('ClickTransaction', clickTransactionSchema);
